/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_askolds_cmptest_opencv_OpenCVStuff */

#ifndef _Included_org_askolds_cmptest_opencv_OpenCVStuff
#define _Included_org_askolds_cmptest_opencv_OpenCVStuff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_askolds_cmptest_opencv_OpenCVStuff
 * Method:    otsu
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_askolds_cmptest_opencv_OpenCVStuff_otsu
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint);

/*
 * Class:     org_askolds_cmptest_opencv_OpenCVStuff
 * Method:    colorIndex
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;DDD)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_askolds_cmptest_opencv_OpenCVStuff_colorIndex
  (JNIEnv *, jobject, jstring, jstring, jstring, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
